version: 2.1

orbs:
  python: circleci/python@0.3.0

jobs:
  build-and-test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: py.test test_device.py
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
